blog/urls.py
from django.urls import path

from blog.feeds import LatestPostFeed
from blog.views import (
    post_list_view, post_detail_view,
    PostListView, post_share_view,
)

app_name = 'blog'

urlpatterns = [
    # path('', post_list_view, name='list'),
    # path('tag/<slug:slug_tag>/', post_list_view, name='list_by_tag'),
    path('', PostListView.as_view(), name='list'),
    path('tag/<slug:slug_tag>/', PostListView.as_view(), name='list_by_tag'),
    path('<int:year>/<int:month>/<int:day>/<slug:post>/', post_detail_view, name='detail'),
    path('<int:post_id>/share/', post_share_view, name='share'),
    path('feed/', LatestPostFeed(), name='post_feed'),
]

my_site/urls.py
from django.contrib import admin
from django.urls import path, include
from django.contrib.sitemaps.views import sitemap
from blog.sitemaps import PostSitemap

sitemaps = {'posts': PostSitemap, }

urlpatterns = [
    path('admin/', admin.site.urls),
    path('blog/', include('blog.urls', namespace='blog')),
    path('sitemap.xml', sitemap, {'sitemaps': sitemaps, },
         name='django.contrib.sitemaps.views.sitemap'),
]

templates/base.html
{% load blog_tags %}
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>{% block title %}{% endblock %}</title>
    <link rel="stylesheet" href="{% static 'css/style.css' %}">
</head>
<body>
<div id="content">

    {% block content %}
    {% endblock %}
    <form action="{% url 'blog:list' %}" method="get">
        <input type="text" name="query" placeholder="enter here">
        <input type="submit" value="Search">
    </form>
</div>
<div id="sidebar">


    <h2><a href="{% url 'blog:list' %}">Blog</a></h2>
    <p>This is my blog. I've written {% total_posts %} posts so far</p>
    <p><a href="{% url 'blog:post_feed' %}">Subscribe to my RSS feed</a></p>
    <h3>Latest posts</h3>
    {% show_latest_posts 3 %}
    <h3>Most commented posts</h3>
    {% get_most_commented_posts as most_commented_posts %}
    <ul>
        {% for post in most_commented_posts %}
        <li>
            <a href="{{ post.get_absolute_url }}">{{ post }} ({{ post.count }} comments)</a>
        </li>
        {% endfor %}

    </ul>
    <a href="{% url 'blog:list' %}"><h2>back</h2></a>


</div>


</body>
</html>